name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@2
      
    - name: Login using Username and Docker Token
      uses: docker/login-action@2
      with: 
        username : ${{ secrets.DOCKER_REPO_NAME }}
        password: ${{ secrets.DOCKER_REPO_PASSWORD }}
      
    - name: Build and Push Image
      uses: docker/build-push-action@3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPO_NAME }}/rest-extension:latest
        
    - name: Cleanup and Exit
      run: echo "Build Finished and Exiting Processes"
        
      
      
    
    
