name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Login using Username and Docker Token
        uses: docker/login-action@v1
        with: 
          username : ${{ secrets.DOCKER_REPO_NAME }}
          password: ${{ secrets.DOCKER_REPO_PASSWORD }}
          
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO_NAME }}/rest-extension:latest

      - name: Cleanup and Exit
        run: echo "Build Finished and Exiting Processes"
        
      
      
    
    
